[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 999999
remappings = [
  '@optimism/packages/contracts-bedrock=lib/optimism/packages/contracts-bedrock',
  '@openzeppelin/contracts-upgradeable/=lib/optimism/packages/contracts-bedrock/lib/openzeppelin-contracts-upgradeable/contracts',
  '@openzeppelin/contracts/=lib/optimism/packages/contracts-bedrock/lib/openzeppelin-contracts/contracts',
  '@rari-capital/solmate/=lib/optimism/packages/contracts-bedrock/lib/solmate',
  '@cwia/=lib/optimism/packages/contracts-bedrock/lib/clones-with-immutable-args/src',
  '@lib-keccak/=lib/optimism/packages/contracts-bedrock/lib/lib-keccak/contracts/lib',
  'safe-contracts/=lib/optimism/packages/contracts-bedrock/lib/safe-contracts/contracts',
  'kontrol-cheatcodes/=lib/optimism/packages/contracts-bedrock/lib/kontrol-cheatcodes/src',
  'solady/=lib/optimism/packages/contracts-bedrock/lib/solady/src',  
  
  'forge-std/=lib/forge-std/src',
  'ds-test/=lib/forge-std/lib/ds-test/src',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config